apiVersion: v1
name: kruise
description: Helm chart for all kruise components
version: 0.1.0
#kubeVersion: ">=1.10.0"
keywords:
  - kruise
  - workload
  - statefulset
  - sidecar
home: https://openkruise.io
sources:
  - https://github.com/openkruise/kruise
