# Default values for kruise.

# settings for log print
log:
  # log level for kruise-manager
  level: "4"

# image settings
image:
  # repository for kruise-manager image
  repository: openkruise/kruise-manager
  # tag for kruise-manager image
  tag: v0.1.0

# resources of kruise-manager container
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 60Mi
