# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2
jobs:
  markdownlint-misspell-shellcheck:
    docker:
      # this image is build from Dockerfile 
      # https://github.com/pouchcontainer/pouchlinter/blob/master/Dockerfile
      - image: pouchcontainer/pouchlinter:v0.1.2
    working_directory: /go/src/github.com/openkruise/kruise
    steps:
      - checkout
      - run:
          name: use markdownlint v0.5.0 to lint markdown file (https://github.com/markdownlint/markdownlint)
          command: |
            find  ./ -name  "*.md" | grep -v vendor | grep -v commandline |  grep -v .github |  grep -v swagger |  grep -v api |  xargs mdl -r ~MD010,~MD013,~MD022,~MD024,~MD029,~MD031,~MD032,~MD033,~MD036
      - run:
          name: use markdown-link-check(https://github.com/tcort/markdown-link-check) to check links in markdown files
          command: |
            set +e
            for name in $(find . -name \*.md | grep -v vendor | grep -v CHANGELOG); do 
              if [ -f $name ]; then 
                markdown-link-check -q $name -c .circleci/markdown-link-check.config.json;
                if [ $? -ne 0 ]; then
                  code=1
                fi
              fi 
            done 
            bash -c "exit $code";
      - run:
          name: use opensource tool client9/misspell to correct commonly misspelled English words 
          command: |
            find  ./* -name  "*"  | grep -v vendor | xargs misspell -error
      - run:
          name: use ShellCheck (https://github.com/koalaman/shellcheck) to check the validateness of shell scripts in pouch repo
          command: |
            find ./ -name "*.sh" | grep -v vendor | xargs shellcheck
  code-check:
    docker: 
      - image: golangci/golangci-lint:v1.21
    working_directory: /go/src/github.com/openkruise/kruise
    steps:
      - checkout
      - run: 
          name: validate go code with golangci-lint
          command: |
            golangci-lint run --skip-dirs=apis,pkg/client --disable-all -E gofmt -E goimports -E golint -E ineffassign -E misspell -E vet
      
      - run:
          name: detect deadcode without test folder
          command: |
            golangci-lint run --disable-all --skip-dirs=vendor,test,pkg/client -E deadcode

workflows:
  version: 2
  ci:
    jobs:
      - markdownlint-misspell-shellcheck
      - code-check
