apiVersion: apps.kruise.io/v1alpha1
kind: UnitedDeployment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uniteddeployment-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "foo"
  template:
    statefulSetTemplate:
      metadata:
        labels:
          app: foo
      spec:
        containers:
        - name: "nginx"
          image: "nginx:1.0"
  topology:
    subsets:
    - name: "subsetA"
      nodeSelector:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "node"
            operator: "In"
            values:
            - "zoneA"



