name: "Create cluster using KinD"
on: push

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.1.0
    - name: setup-k8s and install kruise
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        echo $KUBECONFIG
        kubectl cluster-info
        kubectl get pods -n kube-system
        kubectl apply -f ./config/crds/
        kubectl apply -f ./config/manager/all_in_one.yaml
    - name: e2e-test
      run: |
        APP_PATH=/home/runner/go/src/github.com/openkruise/kruise
        mkdir -p $APP_PATH
        cp -r ./ $APP_PATH
        cd $APP_PATH
        go test ./test/e2e/ -timeout 60m -v -args "-kubeconfig=/home/runner/.kube/kind-config-kind"